apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: maaletriveniacr243142.azurecr.io/webapp:replaced_tag 
        resources:
          requests:
            cpu: "0.1"
            memory: "64Mi"
          limits:
            memory: "250Mi"
            cpu: "0.3"
        ports:
        - containerPort: 8080  
        imagePullPolicy: Always
        

